version: "3.7"

services:
  web:
    image: ${web_image}
    command: gunicorn MAT.config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/srv/mat-api/static
    ports:
      - 8000:8000
    env_file: .env
  nginx:
    image: ${ngix_image}
    volumes:
      - static_volume:/srv/mat-api/static
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
