version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
      cache_from:
        - ${web_image}
    image: ${web_image}
    command: gunicorn MAT.config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/srv/mat-api/static
    expose:
      - 8000
    env_file: .env
  nginx:
    build:
      context: ./nginx
      cache_from:
        - ${nginx_image}
    image: ${nginx_image}
    volumes:
      - static_volume:/srv/mat-api/static
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
