# Generated by Django 3.0.2 on 2020-01-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='start_date',
        ),
        migrations.AddField(
            model_name='cohort',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
