# Generated by Django 3.0.5 on 2020-04-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecords',
            name='checked_in_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='attendancerecords',
            name='checked_out_time',
            field=models.TimeField(null=True),
        ),
    ]
