# Generated by Django 3.0.4 on 2020-04-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecomment',
            name='tag',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
