# Generated by Django 3.0.2 on 2020-01-28 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200128_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='last_name',
        ),
    ]
