# Generated by Django 3.0.5 on 2020-05-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200423_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecords',
            name='attendance_number',
            field=models.FloatField(default=0),
        ),
    ]
