# Generated by Django 3.0.5 on 2020-04-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_attendancecomment_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecords',
            name='checked_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecords',
            name='checked_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
