# Generated by Django 3.0.3 on 2020-02-06 08:10

import datetime
from django.db import migrations, models
import django.db.models.manager
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_students_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cohort',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AlterModelManagers(
            name='cohort',
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='cohort',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cohort',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 2, 6, 8, 10, 21, 804861, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cohort',
            name='deleted',
            field=models.BooleanField(default=False, help_text='This is to make sure deletes are not actual deletes'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
