# Generated by Django 3.0.5 on 2020-04-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200414_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecomment',
            name='check_in_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancecomment',
            name='check_out_comment',
            field=models.BooleanField(default=False),
        ),
    ]
