# Generated by Django 3.0.3 on 2020-02-06 15:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('students', '0005_remove_cohort_date_created'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
        ('staff', '0002_auto_20200129_1436'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffList',
            new_name='Staff',
        ),
    ]
