# Generated by Django 3.0.6 on 2020-09-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200707_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='student_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
