# Generated by Django 3.1.2 on 2020-10-27 14:51

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_delete_tmprofile'),
        ('profiles', '0004_auto_20200907_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, help_text='This is to make sure deletes are not actual deletes')),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.URLField(blank=True, default='https://res.cloudinary.com/mat-api/image/upload/v1589887195/profilepic_ilcie7.png', null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Male', max_length=30)),
                ('student_class', models.CharField(blank=True, max_length=255, null=True)),
                ('fullname', models.CharField(default='firstname lastname', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
            ],
            options={
                'db_table': 'student_profile',
            },
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
