# Generated by Django 3.1.2 on 2021-02-22 12:52

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20201027_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCurrentTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, help_text='This is to make sure deletes are not actual deletes')),
                ('is_active', models.BooleanField(default=True)),
                ('track', models.CharField(choices=[('prep', 'Prep'), ('angular', 'Angular'), ('flask', 'Flask'), ('java', 'Java'), ('django', 'Django'), ('android', 'Android'), ('dsprep', 'DSPrep'), ('dscore', 'DSCore')], default='prep', max_length=30)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.studentcurrenttrack'),
        ),
    ]
