# Generated by Django 3.0.3 on 2020-02-27 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0002_historicalcohort'),
        ('authentication', '0007_historicaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='cohort',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cohorts.Cohort'),
        ),
        migrations.AddField(
            model_name='user',
            name='cohort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='cohorts.Cohort'),
        ),
    ]
