# Generated by Django 3.0.6 on 2020-08-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0002_historicalcohort'),
        ('authentication', '0009_auto_20200824_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cohort',
            field=models.ManyToManyField(blank=True, related_name='members', to='cohorts.Cohort'),
        ),
    ]
