# Generated by Django 3.0.6 on 2020-09-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0002_historicalcohort'),
        ('authentication', '0010_auto_20200827_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cohort',
            field=models.ManyToManyField(related_name='members', to='cohorts.Cohort'),
        ),
    ]
