# Generated by Django 3.0.6 on 2020-09-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0002_historicalcohort'),
        ('authentication', '0011_auto_20200907_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cohort',
            field=models.ManyToManyField(blank=True, related_name='members', to='cohorts.Cohort'),
        ),
    ]
