# Generated by Django 3.0.6 on 2020-10-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20200910_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='is_podleader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_podleader',
            field=models.BooleanField(default=False),
        ),
    ]
