# Generated by Django 3.1.2 on 2020-10-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20201025_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='email',
            field=models.CharField(db_index=True, max_length=255, verbose_name='email of User'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='type',
            field=models.CharField(choices=[('TM', 'Tm'), ('STUDENT', 'Student'), ('POD_LEADER', 'PodLeader'), ('ADMIN', 'Admin')], default='ADMIN', max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True, verbose_name='email of User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('TM', 'Tm'), ('STUDENT', 'Student'), ('POD_LEADER', 'PodLeader'), ('ADMIN', 'Admin')], default='ADMIN', max_length=50, verbose_name='Type'),
        ),
    ]
