# Generated by Django 3.1.2 on 2020-10-26 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_tmprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tmprofile',
            table='tm_profile',
        ),
    ]
