# Generated by Django 3.1.2 on 2020-10-27 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_auto_20201026_1416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TmProfile',
        ),
    ]
