# Generated by Django 3.1.2 on 2020-10-30 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_delete_tmprofile'),
        ('authentication', '0014_cohortmembership_current_cohort'),
    ]

    operations = [
    ]
