# Generated by Django 3.1.2 on 2020-10-28 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_delete_tmprofile'),
        ('authentication', '0013_auto_20201027_1502'),
    ]

    operations = [
    ]
