# Generated by Django 3.1.2 on 2020-11-20 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_auto_20201028_2037'),
        ('authentication', '0018_merge_20201030_1026'),
    ]

    operations = [
    ]
