# Generated by Django 3.1.2 on 2021-03-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_merge_20201120_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
    ]
