# Generated by Django 3.0.6 on 2020-10-27 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0002_historicalcohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 10, 27)),
        ),
        migrations.AddField(
            model_name='cohort',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 10, 27)),
        ),
        migrations.AddField(
            model_name='historicalcohort',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 10, 27)),
        ),
        migrations.AddField(
            model_name='historicalcohort',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 10, 27)),
        ),
    ]
