# Generated by Django 3.0.6 on 2020-10-27 06:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0003_auto_20201027_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 27, 6, 49, 8, 424431, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 27, 6, 49, 8, 424404, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalcohort',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 27, 6, 49, 8, 424431, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalcohort',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 27, 6, 49, 8, 424404, tzinfo=utc)),
        ),
    ]
