# Generated by Django 3.0.6 on 2020-10-27 08:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0004_auto_20201027_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 26, 8, 59, 11, 99315, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalcohort',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 26, 8, 59, 11, 99315, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalcohort',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
