# Generated by Django 3.0.6 on 2020-10-27 12:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0006_auto_20201027_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 9, 12, 2, 50, 558311, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalcohort',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 9, 12, 2, 50, 558311, tzinfo=utc)),
        ),
    ]
