# Generated by Django 3.1.2 on 2020-10-28 17:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0007_auto_20201027_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 10, 17, 37, 41, 455144, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalcohort',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 10, 17, 37, 41, 455144, tzinfo=utc)),
        ),
    ]
