# Generated by Django 3.1.2 on 2020-11-27 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0013_auto_20201112_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 3, 12), null=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcohort',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 3, 12), null=True),
        ),
        migrations.AlterField(
            model_name='historicalcohort',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
