# Generated by Django 3.1.2 on 2020-11-27 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0014_auto_20201127_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 3, 13), null=True),
        ),
        migrations.AlterField(
            model_name='historicalcohort',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 3, 13), null=True),
        ),
    ]
