# Generated by Django 3.1.2 on 2021-02-13 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0016_auto_20210201_0723'),
        ('cohorts', '0016_auto_20210203_1235'),
    ]

    operations = [
    ]
