# Generated by Django 3.1.2 on 2021-03-02 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0017_merge_20210215_1300'),
        ('cohorts', '0017_merge_20210213_1104'),
    ]

    operations = [
    ]
