# Generated by Django 3.1.2 on 2021-04-12 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0016_auto_20210119_1102'),
        ('cohorts', '0018_merge_20210302_1005'),
    ]

    operations = [
    ]
